export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const LOAD_ALL_ALBUMS = 'LOAD_ALL_ALBUMS';
export const LOAD_IMAGE = 'LOAD_IMAGE';
export const SELECT_ALBUM = 'SELECT_ALBUM';
export const SELECT_IMAGE = 'SELECT_IMAGE';
export const RESET_SELECTED_IMAGE = 'RESET_SELECTED_IMAGE';
export const RESET_SELECTED_ALBUM = 'RESET_SELECTED_ALBUM';
